export class LocalStorageKeys {
    public static readonly TAEGLICHE_ARBEITSZEIT_KEY = 'TAEGLICHE_ARBEITSZEIT';
    public static readonly PAUSENLAENGE_KEY = 'PAUSENLAENGE';
    public static readonly PAUSENREGELUNG_KEY = 'PAUSENREGELUNG';
    public static readonly WAS_WAERE_WENN_ACTIVATED_KEY = 'WAS_WAERE_WENN_ACTIVATED';
    public static readonly EINSTEMPELZEIT_RAW_KEY = 'EINSTEMPELZEIT_RAW';
    public static readonly LAST_UPDATE_ON_EINSTEMPELZEIT_KEY = 'LAST_UPDATE_ON_EINSTEMPELZEIT';
    public static readonly LAST_USED_APP_VERSION_KEY = 'LAST_USED_APP_VERSION';
    public static readonly JETZT_OPTION_ACTIVATED_BY_DEFAULT_KEY = 'JETZT_OPTION_ACTIVATED_BY_DEFAULT';
    public static readonly EINSTEMEPELVERHALTEN = 'EINSTEMEPELVERHALTEN';
    public static readonly EINSTEMPEL_ZURUECKDATIERUNG_IN_MINUTEN_KEY = 'EINSTEMPEL_ZURUECKDATIERUNG_IN_MINUTEN';
}
